
# each item under services section is a seperate container
# ports structure: host_port : container_port
# volumes structure: 
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # used for messaging protocol
      - "15672:15672"   # used for rabbitMQ web dashboard
    healthcheck:
      # runs a command inside the container to check if RabbitMQ is ready.
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s        # check every 5 seconds
      timeout: 5s         # only allowed checking for 5s
      retries: 10         # if 10 check fails then the container is unhealthy
      start_period: 10s   # grace period before health checks start
  
  auth-service:
    # builds this container by using the dockerfile inside folder auth-service
    build: ./main-services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      DB_URL: ${USER_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      # maps local folder to container folder -> share common code between services
      - ./shared:/shared
      - ./main-services/auth-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      # container only starts after mongodb is running and rabbitmq passsed health check
      rabbitmq:
        condition: service_healthy

  customer-service:
    build: ./main-services/customer-service
    container_name: customer-service
    ports:
      - "3002:3002"
    environment:
      DB_URL: ${USER_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/customer-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  employee-service:
    build: ./main-services/employee-service
    container_name: employee-service
    ports:
      - "3003:3003"
    environment:
      DB_URL: ${USER_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/employee-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  equipment-service:
    build: ./main-services/equipment-service
    container_name: equipment-service
    ports:
      - "3004:3004"
    environment:
      DB_URL: ${EQUIPMENT_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/equipment-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  room-service:
    build: ./main-services/room-service
    container_name: room-service
    ports:
      - "3005:3005"
    environment:
      DB_URL: ${ROOM_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/room-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  discount-service:
    build: ./main-services/discount-service
    container_name: discount-service
    ports:
      - "3006:3006"
    environment:
      DB_URL: ${DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/discount-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./main-services/notification-service
    container_name: notification-service
    ports:
      - "3007:3007"
    environment:
      DB_URL: ${DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ./shared:/shared
      - ./main-services/notification-service:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  api-gateway:
    # this service acts as the entry point for clients
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/shared
    depends_on:
      - auth-service
      - customer-service
      - employee-service
      - equipment-service
      - room-service
      - discount-service
      - notification-service

